### ISSUE TITLE
Inventory notification

### ISSUE THREAD

**Issue by noraj** [CasperGN/ActiveDirectoryEnumeration#28]
As I was able to test your tool and found it useful, I added it on [*Rawsec's CyberSecurity Inventory*](https://inventory.rawsec.ml/).

https://inventory.rawsec.ml/tools.html#ActiveDirectoryEnumeration

The following it the standard inventory notification template :smiley: this is just informative

### What is Rawsec's CyberSecurity Inventory?

An inventory of tools and resources about CyberSecurity. This inventory aims to help people to find everything related to CyberSecurity.

![](https://i.imgur.com/iLNgnlz.png)

More details about features [here](https://inventory.rawsec.ml/features.html).

Note: the inventory is a FLOSS (Free, Libre and Open-Source Software) project.

### Why should you care about being inventoried?

Mainly because this is giving visibility to your tool and improve its referencing.

### Badges

The badge shows to your community that your are inventoried. It looks good but also shows you care about your project, that your tool is referenced.

Feel free to claim your badge here: http://inventory.rawsec.ml/features.html#badges, it looks like that [![Rawsec's CyberSecurity Inventory](https://inventory.rawsec.ml/img/badges/Rawsec-inventoried-FF5050_flat.svg)](https://inventory.rawsec.ml/), but there are several styles available.

### Want to thank us?

If you want to thank us, you can help make our open project better known by tweeting about it! For example: [![Twitter URL](https://img.shields.io/twitter/url/https/rawsec_cyber.svg?label=rawsec&style=social)](https://twitter.com/intent/tweet?text=We%20have%20been%20inventoried%20on%20%23Rawsec%20CyberSecurity%20Inventory%21%20Check%20their%20awesome%20inventory%20of%20tools%20and%20resources%20about%20CyberSecurity%3A%20https%3A//inventory.rawsec.ml/%21%20Thx%20@rawsec_cyber)

### So what?

That's all, this message is just to notify you if you care. Else you can close this issue.

**Comment by noraj** [comment]
@CasperGN I also added your tool to [blackarch](https://blackarch.org/).

https://github.com/BlackArch/blackarch/pull/2770/files

As soon as it will have been merged and the pkgbuild built in the BA repos, you will be able to use this badge.

```
[![Packaging status](https://repology.org/badge/vertical-allrepos/activedirectoryenum.svg)](https://repology.org/project/activedirectoryenum/versions)
```

Here an example for another package

[![Packaging status](https://repology.org/badge/vertical-allrepos/haiti.svg)](https://repology.org/project/haiti/versions)

Installing your tool on BlackArch linux will be as easy as `pacman -S activedirectoryenum`

**Comment by CasperGN** [comment]
Awesome!
I'll take it for a spin as soon as i get the time!

**Comment by noraj** [comment]
In your future dev process, if you plan to modify some dependencies or the architecture of the repo, it would be very appreciated if you open an issue on BA repo so one of us (BA dev) can fix the package quickly accordingly to your change.

Cheer mate and thanks for your great tool.

**Comment by CasperGN** [comment]
Absolutely.
I have plans to make it modular and as more proper package with submodules. The work is ongoing in the branch `modular-v1.x` but I recon it will take more time to finish and include the modules I'd want for a version 1.x as well as test it thorough enough :-)
Im super pleased you find it usefull and very honored you've taken the PR to BA!

**Comment by noraj** [comment]
`activedirectoryenum` is in BA repos for several weeks now, I'll close this issue.

**Comment by noraj** [comment]
BA repos use the release (last is 0.5.0 from sept 2020) on pypi cf [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/activedirectoryenum/PKGBUILD). Should we move to a git package, because it seems there have been a lot of changes that are not released?

**Comment by CasperGN** [comment]
@noraj I think that would make sense. I try my best to keep packages updated through regular dependabot merge requests and only update the actual package build on changes to the code.
I could also consider establishing a workflow up updating the hotfix version (semantic versioning) on dependabot merge requests that get merged to main but that would require a bit of testing back and forth on my end which, unfortunately, I don't have so much time to do as of now.
